### ISSUE TITLE
I got error at build time in Xcode Version 10.0 (10A255)

### ISSUE THREAD

**Issue by Jay-iTechPioneer** [stripe/stripe-ios#1053]
could not decode input file using specified encoding: Unicode (UTF-16), and the file contents appear to be encoded in Unicode (UTF-8) Localizable.strings

**Comment by csabol-stripe** [comment]
@Jay-iTechPioneer we're still on Xcode 9 for internal development but I'll take a look at this as it should be an ~easy fix. Thanks!

**Comment by csabol-stripe** [comment]
Should be fixed now. Let me know you if encounter any other issues. Thanks!

**Comment by annphan** [comment]
@csabol-stripe Any ideas why I have just downloaded latest code but still have this issue. I have checked the file you made changes but it still doesn't work for me. I am using Xcode 10.1 (10B61)

**Comment by csabol-stripe** [comment]
@annphan sorry you're still seeing issues. To clarify you are still getting a "could not decode input file using specified encoding" issue?

**Comment by zuchie** [comment]
Xcode sees UTF-8 encoded contents in file `Localizable.strings (Norwegian Bokmal)`, changing from UTF-16 to UTF-8 in File inspector-Text Settings-Text Encoding could be a temp solution.

**Comment by csabol-stripe** [comment]
ah, yeah Norwegian Bokmal came from a different localization source so I missed that on my last update for this. PR is out
