### ISSUE TITLE
crash in STPImageLibrary.safeImageNamed on Mac Catalyst (intel) in Stripe (21.0.1)

### ISSUE THREAD

**Issue by rocketnik** [stripe/stripe-ios#1722]
## Summary
I am using an STPPaymentCardTextField, that I added via Interface builder. When running the App with Mac Catalyst, opening the screen immediately leads to a crash. Library version:
Stripe (21.0.1)
It does not crash on iOS devices.
It did not crash on any device (including mac Catalyst) in Stripe (19.x.x) - it was still PaymentCardTextField back then I think.

## Code to reproduce
Just when loading the view.

## iOS version
macOS 10.15.7

## Installation method
cocoapods

## SDK version
21.0.1

## Other information
Crashing when force unwrapping the image at the end of
STPImageLibrary.safeImageNamed

Here is the stack trace:
#4	0x0000000102165502 in static STPImageLibrary.safeImageNamed(_:templateIfAvailable:) at FoodRunner/Pods/Stripe/Stripe/STPImageLibrary.swift:172
#5	0x0000000102165e13 in static STPImageLibrary.brandImage(for:template:) at FoodRunner/Pods/Stripe/Stripe/STPImageLibrary.swift:207
#6	0x000000010216448b in static STPImageLibrary.cardBrandImage(for:) at FoodRunner/Pods/Stripe/Stripe/STPImageLibrary.swift:80
#7	0x00000001021a2426 in static STPPaymentCardTextField.brandImage(for:) at FoodRunner/Pods/Stripe/Stripe/STPPaymentCardTextField.swift:519
#8	0x00000001021a2f22 in STPPaymentCardTextField.brandImageView.getter at FoodRunner/Pods/Stripe/Stripe/STPPaymentCardTextField.swift:554
#9	0x00000001021a9fca in STPPaymentCardTextField.commonInit() at FoodRunner/Pods/Stripe/Stripe/STPPaymentCardTextField.swift:635
#10	0x00000001021a81e6 in STPPaymentCardTextField.init(coder:) at FoodRunner/Pods/Stripe/Stripe/STPPaymentCardTextField.swift:610
#11	0x00000001021a8273 in @objc STPPaymentCardTextField.init(coder:) ()

**Comment by rocketnik** [comment]
The reason is, the images are not part of the pods xcproj. The are still there, but they are not compiled into the application. There might be something wrong with your cocoapods setup.

**Comment by davidme-stripe** [comment]
Hey @rocketnik, thanks for filing this, and sorry for the inconvenience! This seems similar to https://github.com/stripe/stripe-ios/issues/1655. I've tried many scenarios of upgrading from 19.x.x, but can't reproduce it locally.

And in my sample project, it seems like Stripe.xcassets (which contains the images) is being built in Cocoapods' auto-generated Pods.xcodeproj:
![image](https://user-images.githubusercontent.com/52758633/100662569-edaa1100-3309-11eb-9d64-0fbb76821d46.png)

To help us debug this, could you help with a few other questions?
* In the `Pods` project, is the `Stripe-Stripe` bundle target being built, and does the `Build Phases -> Copy Bundle Resources` step contain `Stripe.xcassets`?
* In your compiled .app, does `Frameworks/Stripe.framework/Stripe.bundle` exist? Does a `Stripe.bundle` appear anywhere in the .app bundle?

**Comment by rocketnik** [comment]
> In the Pods project, is the Stripe-Stripe bundle target being built, and does the Build Phases -> Copy Bundle Resources step contain Stripe.xcassets?
No

> In your compiled .app, does Frameworks/Stripe.framework/Stripe.bundle exist?
Yes

> Does a Stripe.bundle appear anywhere in the .app bundle?
Yes
It contains all the files listed in the Copy Resources Build Phase of Stripe-Stripe, which lacks the Stripe.xcassets.

I added the assets manually in the pods project, cleaned and recompiled the project: It did not help.

I added the assets manually to my target's build phase: it worked.

I noticed the change from 19.x to 21.x in the Podsspec. looks good to me:
old: s.ios.resource_bundle            = { 'Stripe' => 'Stripe/Resources/**/*' }
new: s.ios.resource_bundle            = { 'Stripe' => 'Stripe/Resources/**/*.{lproj,json,png,xcassets}' }

**Comment by davidme-stripe** [comment]
Interesting, thanks for the information! It's very weird that Cocoapods isn't adding the `xcassets` in specific configs. I have a potential fix: Could you try setting your Stripe pod to this branch in your `Podfile` then running `pod update`?

`pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'davidme/fix-resourcebundles'`

**Comment by eoinoconnell** [comment]
If it's any help I ran into this issue too on iOS. Neither `Stripe` or `Stripe-Stripe` bundle target had the xcassets in the copy bundle resources. Adding them to the Stripe target resolved the issue.

Pods - 1.10.0
Xcode - 12.2
Stripe - 21.0.1

**Comment by davidme-stripe** [comment]
I've applied the above change to version `21.1.0`, which we've just released. Try it out and let me know if you're still experiencing the issue.

**Comment by eoinoconnell** [comment]
Still happening for me on 21.1.0

Just to confirm ran `pod deintegrate` to get rid of everything and pod installed 21.1.0

`Stripe-Stripe` target has Stripe.xcassets 
`Stripe` did *not* have Stripe.xcassets and adding them in Copy Bundle Resources resolves the issue

Let me know if theres any other information that would help

**Comment by rocketnik** [comment]
I have also checked version 21.1.0. It does not resolve the issue.

**Comment by dathu7728** [comment]
Can you @rocketnik  @eoinoconnell @davidme-stripe  share sample application for stripe integrated one

**Comment by mikeAttia** [comment]
I am running into the same issue here on iOS.
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file Stripe/STPImageLibrary.swift, line 172
2020-12-18 10:19:47.645289+0100 VanOnGo[1344:345369] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file Stripe/STPImageLibrary.swift, line 172
```

I upgraded directly from `19.x.x` to `21.1.0`

The `Stripe-Stripe` target has Stripe.xcassets in the Copy Bundle Resources step.
And the `Stripe` target has `Stripe.bundle` in the Copy Bundle Resources step.

When I tried to print the Stripe resources bundle path from `STPBundleLocator.stripeResourcesBundle`
I get this:
```
NSBundle </var/containers/Bundle/Application/C6F3C41A-1203-4CEB-BB0D-8EE0A41456F1/VanOnGo.app/Frameworks/Stripe.framework/Stripe.bundle> (not yet loaded)
```

I checked the directory and it does have the `Stripe.bundle` in that path which does contain the xcassets directory with the images, but why is it `not yet loaded` ?

**Comment by davidme-stripe** [comment]
We still can't reproduce this locally, but thank you for the additional information! This bit is very suspicious to me:
>  it does have the `Stripe.bundle` in that path which does contain the xcassets directory with the images

If Xcode is processing the images correctly, that path should contain an `Assets.car` file, not an `.xcassets` folder containing the images. I'll investigate how this could happen.

**Comment by davidme-stripe** [comment]
Hi! This should be fixed in version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0), please give it a try.

**Comment by minhas-tech** [comment]
I am still facing the issue with latest Stripe version. How to solve this issue. Please help.
<img width="1275" alt="Screenshot 2021-05-07 at 1 00 26 PM" src="https://user-images.githubusercontent.com/80686316/117417849-3490d800-af34-11eb-936e-8a8940d2cb88.png">

**Comment by davidme-stripe** [comment]
Hi @minhas-tech, do the images exist in the "Copy Bundle Resources" section of the `Stripe-Stripe` target in your `Pods.xcodeproj`? Is `Stripe.bundle` present in the `Stripe` target in your `Pods.xcodeproj`?
![image](https://user-images.githubusercontent.com/52758633/117479956-cdfcc180-af15-11eb-9526-863c5ce22a74.png)
![image](https://user-images.githubusercontent.com/52758633/117480010-e076fb00-af15-11eb-9694-b2fe898f3787.png)

**Comment by minhas-tech** [comment]
@davidme-stripe , Yes I have these. Google pay and apple pay is working. Pay via card crashes the app. I am working with React native , tipsi stripe and Stripe-IOS

<img width="843" alt="Screenshot 2021-05-10 at 12 40 09 PM" src="https://user-images.githubusercontent.com/80686316/117623396-2ee1ff00-b18d-11eb-82cb-a6923474ede7.png">
<img width="819" alt="Screenshot 2021-05-10 at 12 40 21 PM" src="https://user-images.githubusercontent.com/80686316/117623408-32758600-b18d-11eb-87f3-01b9a5723ba6.png">

**Comment by paschalidi** [comment]
+1 on react native 
```
Stripe (21.6.0)
stripe-react-native (0.1.4)
```

**Comment by davidme-stripe** [comment]
> I get error like this (images are missing) for 1x
@minhas-tech Can you share the exact error message you get? I haven't seen this before, and the system should generally fall back to the 3x images correctly.

**Comment by salehshah** [comment]
Same issue for me. The app crashes when I try to render CardField in the view.

<img width="1321" alt="Screenshot 2021-06-30 at 10 52 01 PM" src="https://user-images.githubusercontent.com/16678445/124008846-4fdd0880-d9f6-11eb-9385-86dc0266207c.png">

**Comment by cdcHub** [comment]
@davidme-stripe any update on this? I'm using the latest version, facing same issue. 
"@stripe/stripe-react-native": "^0.43.0"

Error
StripeUICore/ImageMaker.swift:51: Assertion failed: Failed to find an image named icon_x_standalone

<img width="1434" alt="Image" src="https://github.com/user-attachments/assets/7a3095e1-30c5-41b9-aba5-c8c4653e3424" />

**Comment by chrisjenx** [comment]
OK this is a bug in the way the stripe sdk looks up resources, if you use the root view controller it crashes, I changed to use the updated view controller from the callback and it started working:

Cross posting to hopefully help others

```
func updateUIViewController(_ uiViewController: UIViewController, context: Self.Context) {
        paymentsLauncher.rootViewController = uiViewController
    }
```

**Comment by chrisjenx** [comment]
OK only way I seem to get this to work is literally build the app back to back, the second build must bundle the assets correctly, the first time doesn't.

Could we request that you don't crash the damn app because you can't load a f*ing icon, it's not that important vs taking payment...

**Comment by chrisjenx** [comment]
Still broken: `icon_x_standalone` is missing, from pure Swift/SPM Xcode project now

**Comment by chrisjenx** [comment]
Finally worked around the Stripe-SPM module issues by just manually importing the xcframeworks:

Script for anyone else struggling with this bug: https://gist.github.com/chrisjenx/79fe87fc45a3821afe2715832e3770be
