### ISSUE TITLE
Payment Sheet Display is messed up in Right to Left languages

### ISSUE THREAD

**Issue by azahrtc** [stripe/stripe-ios#2006]
## Summary

Labels are misplaced in Right-to-Left languages

## iOS version
iOS 15.6.1

## SDK version
22.8.0

## Other information
Change the device language to any Right-to-Left display, i.e Arabic, the UI will be messed up
![WhatsApp Image 2022-09-09 at 11 29 02 AM](https://user-images.githubusercontent.com/89908843/189342322-ba782225-9a5f-46f5-8727-df22b2b7baba.jpeg)

**Comment by ramont-stripe** [comment]
Hi @azahrtc,

We just released v22.8.1 which [addresses the layout issues](https://github.com/stripe/stripe-ios/commit/7afba9c6bc29c5f385afc386a554cc1a341dfc26) on Right-to-Left languages. Arabic language support is also in our roadmap, but we don't a timeline to share yet.

I'm closing this issue for now. Feel free to re-open if needed.

**Comment by azahrtc** [comment]
<img width="358" height="352" alt="Image" src="https://github.com/user-attachments/assets/8f869ad3-e285-4e1b-8c75-f16bee7d98e7" />

The issue is not fixed yet, I am using:
- Stripe iOS SDK 27.15.0
- Simulator iPhone 17 Pro Max iOS 26.4
- Device Language: Arabic

**Comment by yuki-stripe** [comment]
@azahrtc can you confirm the version you're using? 27.15.0 isn't a valid version. I'm not able to repro so far.

**Comment by azahrtc** [comment]
Here is the version: [https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#25170-2026-06-08](url)

To reproduce the issue, change the phone/simulator Language to Arabic/العربية. Then try to add a card you will see the UI broken

**Comment by porter-stripe** [comment]
Hi all, this will be added in our release this coming Tuesday the 8th!

**Comment by azahrtc** [comment]
The latest release is still marked as 29.9.0, when will the new patch version get released officially?
