### ISSUE TITLE
`shared` is unavailable in application extensions for iOS

### ISSUE THREAD

**Issue by RichAppz** [stripe/stripe-ios#2853]
## Summary
Since the 23.13.0 release building has been blocked by an extension issue. There has been a change in the codebase of 23.13.0 that is using `UIApplication.shared` which is not available to swift extensions.

<img width="1723" alt="Screenshot 2023-08-14 at 09 01 02" src="https://github.com/stripe/stripe-ios/assets/2961823/4a52feaa-e58a-4cbf-af89-2e642d4104c6">

## iOS version
iOS 16.6

## Installation method
Cocoapods

## SDK version
23.13.0

## Other information
Reverting back to `23.12.0` works fine!

**Comment by sfriedman-stripe** [comment]
Hi @RichAppz, thank you for writing in about this issue. Could you help us understand a little bit more about your use case? What kind of extension are you building?

**Comment by davidme-stripe** [comment]
@RichAppz Should be fixed in `master`: Can you try pointing your Podfile to the `master` branch? For example:
```
target 'MyAppExtension' do
  platform :ios, '13.0'
  use_frameworks!
  pod 'StripeApplePay', git: 'https://github.com/stripe/stripe-ios.git', branch: 'master'
  pod 'StripeCore', git: 'https://github.com/stripe/stripe-ios.git', branch: 'master'
end
```

**Comment by thaissadami** [comment]
I have the same problem, and it still doesn't work. (23.16.0)

**Comment by pascalguizard** [comment]
It still doesn't work for me with xcode 15 and 23.18.2...
Someone have any solution ?

**Comment by davidme-stripe** [comment]
Thanks for the info! Can you share what you're trying to do in the App Extension? STPRedirectContext won't work in an App Extension, as it needs to be able to launch app-to-app redirects, which are not available in App Extensions.

**Comment by pascalguizard** [comment]
I only have Stripe in my pods un use in 1 class in the main app. But this app contains a submodule, a watch app extension and a Today widget extension. Those extensions does not import Stripe.

And when i try to build my app i got this
![image](https://github.com/stripe/stripe-ios/assets/46777763/f10b5919-7cc5-496d-a911-34b2b321c873)

**Comment by davidme-stripe** [comment]
@pascalguizard Can you check your Podfile to confirm that the Stripe pods are not being included in your watch app or Today widget targets? There may also be an [https://guides.cocoapods.org/syntax/podfile.html#inherit_bang](inherit!) entry in one of those targets causing it to build Stripe for application extensions.

If not, it's possible that you're encountering this issue: https://github.com/CocoaPods/CocoaPods/issues/12093

Let me know if that's the case, and we'll keep looking for a solution. Thanks!

**Comment by sfriedman-stripe** [comment]
Hi all, closing this down since we haven't heard from you recently. Please reopen if you're still having issues!

**Comment by KashifJavaid** [comment]
@sfriedman-stripe It happening to me today , while using stripe react native and i created a notification extension and got this same error

**Comment by dineybomfim** [comment]
The issue still very much exists:
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

There are several files in Stripe SDK that needs attention, like HCaptchaURLOpener:

/**
 * UIApplication based implementation
 */
internal class HCapchaAppURLOpener: HCaptchaURLOpener {
    func canOpenURL(_ url: URL) -> Bool {
        return UIApplication.shared.canOpenURL(url)
    }

    func openURL(_ url: URL) {
        UIApplication.shared.open(url, options: [:], completionHandler: nil)
    }
}


The Lib KingFisher has faced the same issue years ago.
The solution is simple, you can just rely on called UIApplication.shared.
This must be properly safe by macros with proper fallback or u can fallback to use OBJC dynamic messaging and then it will be fine.
(check line 870 of a possible solution:
https://github.com/onevcat/Kingfisher/blob/b450a3b30e0767277a6eed7e02dbdebd7d173da0/Sources/Cache/ImageCache.swift#L205)

Or u go with a direct OBJC workaround like:
extension UIApplication {
	
	static var stripeMain: UIApplication { (UIApplication.value(forKeyPath: #keyPath(UIApplication.shared)) as? UIApplication ?? .init()) }
}

Then use it instead of shared:
UIApplication.stripeMain.windows.first { $0.isKeyWindow }
UIApplication.stripeMain.canOpenURL(url)
UIApplication.stripeMain.open(url, options: [:], completionHandler: nil)
UIApplication.stripeMain.stp_hackilyFumbleAroundUntilYouFindAKeyWindow()?.rootViewController?.findTopMostPresentedViewController()
etc...

Should be a straight forward fix... otherwise we have to keep changing the local framework files in order to fix it or use the binary framework version.

Or I can PR the solution for you guys.

**Comment by dineybomfim** [comment]
@yuki-stripe The issue lies in the compiler process, not in the feature level.
As a library, it can't expect to be always directly embedded into main projects. More often nowadays they are embedded into frameworks, submodules, pods, subpods, etc. So while working with SwiftUI which has its own build pipeline and store files different, when working with apps with extensions and compiling targets together, they all hit the same compiler step before stripping. Which is not possible to proceed.

That's main reason why lib like KingFisher put those into Wrapper.
Here is an example:
#if !os(macOS) && !os(watchOS)
// MARK: - For App Extensions
extension UIApplication: KingfisherCompatible { }
extension KingfisherWrapper where Base: UIApplication {
    public static var shared: UIApplication? {
        let selector = NSSelectorFromString("sharedApplication")
        guard Base.responds(to: selector) else { return nil }
        return Base.perform(selector).takeUnretainedValue() as? UIApplication
    }
}
#endif

It's not that the lib or the code will actually be executed, it's about avoiding compiler to statically check for the "shared" UIApplication usage, which is not present in extensions.

**Comment by sfriedman-stripe** [comment]
@dineybomfim App extensions on iOS don't have to share all code with your iOS app, and it is possible to exclude any code that uses Stripe from your app extension build target, which is what we would typically recommend. Unfortunately, we wouldn't be able to help you troubleshoot further without more details about your use case.

**Comment by dineybomfim** [comment]
@sfriedman-stripe that is not correct.
You are thinking purely from a app perspective. As I said problem arrives when you build only frameworks, not apps. You framework has a stripe integration module, which is cocoapods only into an extension, however that is not how the Xcode compiler works for pods and frameworks, it needs to first compile the code.

For me is not a problem, I already cloned Stripe and built my own working solution.
I'm posting purely for the sake of helping others that face the same and use Frameworks.

For everybody else the official Stripe version works.
Also for the sake of sharing if you guys. If you see value on what I say, take it, otherwise leave it.

**Comment by roel-leal** [comment]
Same problem here

`error 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

Someone can do it work?
